### ISSUE TITLE
Padding function gives an incorrect result

### ISSUE THREAD

**Issue by Code-Stars** [piecss/piecss#1]
@include padding((top: 1/2, bottom: 1/2));
padding: rhythm(1/2) 0;

These rules don't give the same result but they should.

**Comment by babsgosgens** [comment]
Output is:
```
.test-padding-function {
  padding-top: 0.25em;
  padding-bottom: 0.25em; }
.test-padding {
  padding: 4px 0; }
```

The resulting values will be equal in the browser, as .25 * 16px (the default font-size) equals 4px.

In practice, the padding and margin functions are not being used. I plan to remove the `sides` utilities in the release 0.8.0.
